<?php

namespace AlRajhi\PaymentGateway\Support;

class ArbErrorCatalog
{
    /**
     * @var array<string, string>
     */
    private const CODES = [
        'IPAY0100335' => 'Duplicate Invoice ID',
        'IPAY0300061' => 'Card Number Should be Numeric.',
        'IPAY0300062' => 'Missing Tranportal Password.',
        'IPAY0300063' => 'Missing Input Data.',
        'IPAY0300064' => 'ECI is empty or null or length is not equal to 2.',
        'IPAY0300066' => 'Problem occurred while updating PreAuth table.',
        'IPAY0300067' => 'Unable to update PreAuthLOG table, payment id is null.',
        'IPAY0300068' => 'Problem occurred while getting connection status from extr connection.',
        'IPAY0300069' => 'Transaction in progress in another tab/window.',
        'IPAY0300071' => 'Problem occurred while inserting Faster Checkout details.',
        'IPAY0300072' => 'Problem occurred while updating PreAuthLog status.',
        'IPAY0300073' => 'Problem occurred while inserting record in PreAuthLog.',
        'IPAY0300074' => 'Problem occurred while validating IMPS transaction.',
        'IPAY0300075' => 'Problem occurred while updating risk factors in Negative card and Declined card',
        'IPAY0300076' => 'Problem occurred while processing original transaction details.',
        'IPAY0300077' => 'Negative bin details not found.',
        'IPAY0300078' => 'Negative card details not found.',
        'IPAY0300079' => 'Not original transaction.',
        'IPAY0300080' => 'Institution id mismatch.',
        'IPAY0300081' => 'Merchant id mismatch.',
        'IPAY0300082' => 'Terminal id mismatch.',
        'IPAY0300083' => 'Invalid captcha.',
        'IPAY0300084' => 'Missing debit card number.',
        'IPAY0300085' => 'Invalid card number length.',
        'IPAY0300086' => 'Missing pin.',
        'IPAY0300087' => 'Invalid pin.',
        'IPAY0300088' => 'Missing expiry month and year.',
        'IPAY0300089' => 'Invalid expiry month and year.',
        'IPAY0300090' => 'Problem occurred while adding payment log details.',
        'IPAY0300092' => 'Problem occurred while validating IMPS.',
        'IPAY0300093' => 'Problem occurred while getting common instrument list.',
        'IPAY0300094' => 'Problem occurred while converting batch data into transaction data.',
        'IPAY0300095' => 'Problem occurred while converting maestro batch data into transaction data.',
        'IPAY0300096' => 'Invalid Common Payment Instrument List.',
        'IPAY0300097' => 'Problem occurred while common payment instrument.',
        'IPAY0300098' => 'Problem occurred during VPAS transaction.',
        'IPAY0300099' => 'Transaction denied due to invalid action Codes',
        'IPAY0300100' => 'Problem occurred while encrypting card details.',
        'IPAY0300101' => 'Problem occurred while generating ISO for transaction data.',
        'IPAY0300102' => 'Problem occurred while generating VISA ISO for transaction data.',
        'IPAY0300103' => 'Problem occurred while generating ISO for VPAS transaction.',
        'IPAY0300104' => 'Problem occurred while generating MASTER ISO for transaction data.',
        'IPAY0300105' => 'Problem occurred while generating VISA ISO for debit transaction.',
        'IPAY0300106' => 'Problem occurred while generating MASTER ISO for debit transaction.',
        'IPAY0300107' => 'Problem occurred while generating ISO for debit transaction.',
        'IPAY0300108' => 'Problem occurred while generating ISO for prepaid transaction.',
        'IPAY0300109' => 'I-Frame Flag is not enabled',
        'IPAY0300110' => 'Rupay transaction not enabled for Terminal.',
        'IPAY0300111' => 'Message got rejected by SM.',
        'IPAY0300112' => 'Unable to process the message.',
        'IPAY0300113' => 'Invalid input.',
        'IPAY0300114' => 'Duplicate message.',
        'IPAY0300115' => 'Request come with GET method so transaction declined.',
        'IPAY0300116' => 'Transaction initiated with invalid source.',
        'IPAY0300117' => 'Invalid Unique id.',
        'IPAY0300118' => 'IP is blocked.',
        'IPAY0300119' => 'IP is not configured to process the message.',
        'IPAY0300120' => 'Remote IP Profile is not configured to process the message.',
        'IPAY0300121' => 'Invalid input format.',
        'IPAY0300122' => 'Connection Read Timeout.',
        'IPAY0300123' => 'Search result greater than maximum number of records allowed. Increase search granularity and re-submit.',
        'IPAY0300124' => 'Problem occurred while verifying tranportal id.',
        'IPAY0300125' => 'Missing required data.',
        'IPAY0300126' => 'Missing data type.',
        'IPAY0300127' => 'Transaction declined due to payment log not updated.',
        'IPAY0300128' => 'Duplicate transaction request.',
        'IPAY0300130' => 'Problem occurred while checking IP range.',
        'IPAY0300131' => 'Problem occurred while checking negative bin range.',
        'IPAY0400001' => 'Problem occurred while getting merchant acknowledgement & transaction reversed.',
        'IPAY0400002' => 'Problem occurred while parsing merchant request.',
        'IPAY0400004' => 'Missing Action.',
        'IPAY0400005' => 'Missing Password.',
        'IPAY0400006' => 'Missing TrackID.',
        'IPAY0400007' => 'Missing Payment Id or Tranportal Id.',
        'IPAY0400008' => 'Missing UDF5.',
        'IPAY0400009' => 'Missing TransID.',
        'IPAY0400010' => 'Missing Card Type.',
        'IPAY0400011' => 'Blank Request.',
        'IPAY0500002' => 'paymentData not enabled.',
        'IPAY0500003' => 'paymentMethod not enabled.',
        'IPAY0500004' => 'Header not enabled.',
        'IPAY0500005' => 'Problem occurred while getting paymentData details.',
        'IPAY0500006' => 'Problem occurred while getting paymentToken details.',
        'IPAY0500007' => 'Problem occurred while getting header details.',
        'IPAY0500008' => 'Problem occurred while getting paymentMethod details.',
        'IPAY0500009' => 'Problem occurred while getting Token details.',
        'IPAY0500010' => 'Asymmetric keys do not match.',
        'IPAY0500011' => 'Problem occurred while processing the CreditInstalment Request.',
        'IPAY0500012' => 'Problem occurred while validating applePay signature.',
        'IPAY0500013' => 'Problem occurred while getting applePay brand details.',
        'IPAY0500014' => 'Problem occurred while processing the applePay tranportal transaction.',
        'IPAY0500015' => '3d secure not enabled for the terminal.',
        'IPAY0500016' => 'signature certificates count missed.',
        'IPAY0500017' => 'leaf certificate missing.',
        'IPAY0500018' => 'intermediate certificate missing.',
        'IPAY0500019' => 'Failed to verify apple pay signature.',
        'IPAY0500020' => 'Failed to extract sign time from apple pay signature.',
        'IPAY0500021' => 'Apple pay signature is too old.',
        'IPAY0500022' => 'Problem occurred while validating applePay signature time.',
        'IPAY0500023' => 'Failed to verify apple pay certificate.',
        'IPAY0500024' => 'Problem occurred while validating rootCA.',
        'IPAY0500025' => 'Exception while initializing Code Signer Certs.',
        'IPAY0500026' => 'Problem occure while framing signedData.',
        'IPAY0500027' => 'Apple pay currency code and transaction currency code not matched.',
        'IPAY0500028' => 'Apple pay amount and transaction amount not matched.',
        'IPAY0500029' => 'Apple pay transaction ID not matched.',
        'IPAY0500030' => 'Problem occurred while inserting record in Applepay Tranlog.',
        'IPAY0500031' => 'Applepay transaction not enabled for Terminal.',
        'IPAY0500032' => 'Applepay merchant not enabled.',
        'IPAY0500033' => 'Problem occurred while getting Applepay merchant details.',
        'IPAY0500034' => 'Payment Data missing.',
        'IPAY0500035' => 'Payment Method missing.',
        'IPAY0500036' => 'Payment Transaction Identifier missing.',
        'IPAY0500037' => 'Problem occurred while getting merchant session.',
        'IPAY0500038' => 'MADA Applepay transaction is not supported.',
        'IPAY0600001' => 'Misssing SI data.',
        'IPAY0660001' => 'Unable to frame the card request due to invalid Serial Number.',
        'IPAY0660002' => 'Unable to frame the card request due to invalid Profile Number.',
        'IPAY0660003' => 'Unable to frame the card request due to invalid User ID.',
        'IPAY0660004' => 'Unable to frame the card request due to invalid Operating system type.',
        'IPAY0660005' => 'Unable to frame the card request due to invalid IP Address.',
        'IPAY0660006' => 'Unable to frame the card request due to invalid card Type.',
        'IPAY0660007' => 'Problem occurred while framing the card fetch request.',
        'IPAY0660008' => 'Problem occurred while fetching the card details for saved card.',
        'IPAY0660009' => 'Problem occurred while fetching the connection details for card list.',
        'IPAY0660010' => 'Card List details are invalid to get the card details.',
        'IPAY0660011' => 'Pan mismatch in Market Place Card List Response message.',
        'IPAY0700001' => 'Credit Instalment flag not enabled.',
        'IPAY0700002' => 'Credit Instalment is not applicable for this bin.',
        'IPAY0700003' => 'Unable to frame credit instalment request.',
        'IPAY0700004' => 'Problem occurred while framing Acquire Ticket request.',
        'IPAY0700005' => 'Credit instalment response is empty.',
        'IPAY0700006' => 'Raw instalment plan data is empty.',
        'IPAY0700007' => 'Failure Result Code Recieved from Prime.',
        'IPAY0700008' => 'Problem occurred while inserting record in CreditInstalmetLog.',
        'IPAY0800001' => 'Apple Pay Payment Details is invalid.',
        'IPAY0800002' => 'Apple Pay Network Indicator is invalid.',
        'IPAY0800003' => 'Apple Pay onlinePaymentCryptogram is invalid.',
        'IPAY0800004' => 'Apple Pay transactionIdentifier is invalid.',
        'IPAY0800005' => 'Apple Pay type is invalid.',
        'IPAY0800006' => 'Apple Pay eci Indicator is invalid.',
        'IPAY0800007' => 'Apple Pay deviceManufacturerIdentifier is invalid.',
        'IPAY0800008' => 'Apple Pay device pan is invalid.',
        'IPAY0800009' => 'Apple Pay device pan expiry details is invalid.',
        'IPAY0800010' => 'Apple Pay currency code is invalid.',
        'IPAY0800011' => 'Apple Pay PSP Flag not enabled for this Merchant.',
        'IPAY0800012' => 'Absher data is invalid.',
        'IPAY0800013' => 'Sector ID is invalid in Absher Payment data.',
        'IPAY0800014' => 'Service code is invalid in Absher Payment data.',
        'IPAY0800015' => 'Beneficiary ID is invalid in Absher Payment data.',
        'IPAY0800016' => 'Beneficiary ID type is invalid in Absher Payment data.',
        'IPAY0800017' => 'Sector ID length is invalid in Absher Payment data.',
        'IPAY0800019' => 'Beneficiary Name is invalid in Absher Payment data.',
        'IPAY0800020' => 'Beneficiary Name length is invalid in Absher Payment data.',
        'IPAY0800021' => 'Branch Code is invalid in Absher Payment data.',
        'IPAY0800022' => 'Branch Code length is invalid in Absher Payment data.',
        'IPAY0800023' => 'Violation details is invalid in Absher Payment data.',
        'IPAY0800024' => 'Violation count is invalid in Absher Payment data.',
        'IPAY0800025' => 'Violation count should be numeric in Absher Payment data.',
        'IPAY0800026' => 'Violation count should be valid length in Absher Payment data.',
        'IPAY0800027' => 'Violation list is invalid in Absher Payment data.',
        'IPAY0800028' => 'Violation list size is invalid in Absher Payment data.',
        'IPAY0800029' => 'Violation id is invalid in Absher Payment data.',
        'IPAY0800030' => 'Violation amount is invalid in Absher Payment data.',
        'IPAY0800031' => 'Sentence details is invalid in Absher Payment data.',
        'IPAY0800033' => 'Number of sentences should be numeric in Absher Payment data.',
        'IPAY0800034' => 'Sentence count should be valid length in Absher Payment data.',
        'IPAY0800035' => 'Sentence list is invalid in Absher Payment data.',
        'IPAY0800036' => 'Sentence list size is invalid in Absher Payment data.',
        'IPAY0800037' => 'Sentence number is invalid in Absher Payment data.',
        'IPAY0800038' => 'Sentence amount is invalid in Absher Payment data.',
        'IPAY0800039' => 'Sentence installment number is invalid in Absher Payment data.',
        'IPAY0800040' => 'Sentence number should be numeric in Absher Payment data.',
        'IPAY0800041' => 'Sentence installment number should be numeric in Absher Payment data.',
        'IPAY0800042' => 'Sentence number should be valid length in Absher Payment data.',
        'IPAY0800043' => 'Sentence installment number should be valid length in Absher Payment data.',
        'IPAY0800044' => 'Missing Sector id.',
        'IPAY0800045' => 'Invalid Sector id.',
        'IPAY0800046' => 'Invalid IP Address.',
        'IPAY0800047' => 'Violation ID length is invalid in Absher Payment data.',
        'IPAY0800048' => 'Payment Inquiry Type is invalid in Absher Payment data.',
        'IPAY0800049' => 'Payment Inquiry Type should be alphanumeric in Absher Payment data.',
        'IPAY0800050' => 'Payment Inquiry Type length is invalid in Absher Payment data.',
        'IPAY0800051' => 'Problem occurred while validating Absher Payment data.',
        'IPAY0800052' => 'Transaction declined due to action type not supported.',
        'IPAY0800053' => 'Invalid Merchant Country Code.',
        'IPAY0800054' => 'Card Not Supported!',
        'IPAY0800055' => 'Mod 10 failed for the card number.',
        'IPAY0800057' => 'Problem occurred while updating Faster Checkout Customer details.',
        'IPAY0800058' => 'Faster Checkout card number already registered.',
        'IPAY0800059' => 'Problem occurred while adding vpas cres details.',
        'IPAY0800060' => 'Problem occurred while getting details from saf dump using ReversalKey.',
        'IPAY0800061' => 'Please try after sometime.',
        'IPAY0860001' => 'Problem occurred while loading default messages in MADA ISO Formatter.',
        'IPAY0860002' => 'Problem occurred while loading default mesages for Supporting in MADA ISO Formatter.',
        'IPAY0860003' => 'Problem occurred while formatting purchase request in MADA ISO Message Formatter.',
        'IPAY0860004' => 'Problem occurred while formatting Credit request in MADA ISO Message Formatter.',
        'IPAY0860005' => 'Problem occurred while formatting Reverse purchase request in MADA ISO Message Formatter.',
        'IPAY0860006' => 'Problem occurred while formatting authorization request in MADA ISO Message Formatter.',
        'IPAY0860007' => 'Problem occurred while formatting Reverse authorization request in MADA ISO Message Formatter.',
        'IPAY0860008' => 'Problem occurred while formatting Authorization extension in MADA ISO Message Formatter.',
        'IPAY0860009' => 'Problem occurred while formatting Capture request in MADA ISO Message Formatter.',
        'IPAY0860010' => 'Problem occurred while formatting Account verification request in MADA ISO Message Formatter.',
        'IPAY0860011' => 'Problem occurred while formatting Administrative Notification request in MADA ISO Message Formatter.',
        'IPAY0860012' => 'Problem occurred while formatting the secure data in MADA ISO Message Formatter.',
        'IPAY0860013' => 'Problem occurred while formatting the request for Supporting transactions in MADA ISO Message Formatter.',
        'IPAY0860014' => 'Problem occurred while formatting the request Authorization supporting transactions in MADA ISO Message Formatter.',
        'IPAY0860015' => 'Problem occurred while formatting the Original transaction data in MADA ISO Message Formatter.',
        'IPAY0860016' => 'Problem occurred while formatting the Original transaction data for Merchant Initiated transactions in MADA ISO Message Formatter.',
        'IPAY0860017' => 'Problem occurred while validating the Recurring Transaction data in MADA ISO Formatter.',
        'IPAY0860018' => 'Problem in getting the key exchange values for MAC generation.',
        'IPAY0860019' => 'Problem occurred while generating the MAC values.',
        'IPAY0860020' => 'MAC key is empty not able to generate MAC values.',
        'IPAY0880001' => 'URPay Transaction is not enabled.',
        'IPAY0880002' => 'Token generation missing data.',
        'IPAY0880003' => 'Token generation response is empty.',
        'IPAY0880004' => 'Problem occuerd while generating Token.',
        'IPAY0880005' => 'Problem occurred while inserting URPay API details table.',
        'IPAY0880006' => 'Problem occurred while selecting URPay otp auth table.',
        'IPAY0880007' => 'Problem occuerd while performing URPay Transaction.',
        'IPAY0880008' => 'OTP token data is not available.',
        'IPAY0880009' => 'Token is empty.',
        'IPAY0880010' => 'OTP validation response is empty.',
        'IPAY0880011' => 'Problem occurred while validating URPay otp.',
        'IPAY0880012' => 'Problem occurred while updating URPay API details table.',
        'IPAY0880013' => 'Problem occurred while updating URPay details.',
        'IPAY0880016' => 'OTP Reverse redemption response is empty.',
        'IPAY0880017' => 'Problem occurred while inserting URPay log details.',
        'IPAY0880018' => 'Problem occurred while deleting vpas pares details.',
        'IPAY0880019' => 'Problem occuerd while generating Otp.',
        'IPAY0880020' => 'Problem occuerd while proccessing resend Otp.',
        'IPAY0880021' => 'Problem occuerd while validating Otp.',
    ];

    public static function normalizeCode(?string $code): ?string
    {
        if ($code === null) {
            return null;
        }

        $upper = strtoupper(trim($code));

        if (preg_match('/(IPAY\d{7})/', $upper, $matches) === 1) {
            return $matches[1];
        }

        return $upper !== '' ? $upper : null;
    }

    public static function messageFor(?string $code): ?string
    {
        $normalized = self::normalizeCode($code);

        if ($normalized === null) {
            return null;
        }

        return self::CODES[$normalized] ?? null;
    }
}
